version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:28
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Python and pip
          command: |
            apk add --no-cache python3 py3-pip  # Install Python 3 and pip
            python3 -m pip install --upgrade pip  # Upgrade pip
      - run:
          name: Install docker-compose
          command: |
            pip install docker-compose --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
